### ISSUE TITLE
Only white interface

### ISSUE THREAD

**Issue by mustafa1024m** [danleeb/GreenJ#1]
Hi, I've built GreenJ but the application only displays a white window, now what?? thanks in advance, Regards.

**Comment by danleeb** [comment]
Hi mustafaa,

we provide an example webpage in the directory path/to/greenj/build/phone. If you want to try GreenJ with our example, change directory to path/to/greenj/build and start GreenJ from there:
$ cd path/to/greenj/build
$ ../bin/linux/GreenJ
You should now see a loading screen; the program is trying to connect to a server (e.g. asterisk sip server)

In addition, there should be a file in your home directory (~/.greenj/settings.conf) where you can change the url of the browsers startpage (defaults to phone/index.html).

You can find instruction on how to create your own phone webpage here: http://www.loremipsum.at/produkte/greenj/library/#en

Hope that helps,
Daniel

**Comment by mustafa1024m** [comment]
Hi Daniel, thank you for the quick response, I tried this:
$ cd path/to/greenj/build
$ ../bin/linux/GreenJ
and all I get is a blank window, also tried build/phone/index.html and it only displays "Verbindung zum Server wird hergestellt " and keeps spinning, should I install a server (asterisk) or can I put a username and password to a online SIP account or what?

**Comment by danleeb** [comment]
To test whether the browser is working correctly, you could change the url in ~/.greenj/settings.conf to url=http://www.google.com
or set an absolute path like url=/home/user/GreenJ/build/phone/index.html

We use our own server, but using an existing SIP account should work: In our phone example, the sip account can be configured in phone/js/testphone.js: enter the host (sip server realm), your user and password (secret)

**Comment by mustafa1024m** [comment]
Tried both, blank page, so the browser is not working correctly, what should I do? this is the command line output:

mustafa@localhost:~/VoIP/GreenJ/bin/linux$ ./GreenJ 
 13:55:35.381 os_core_unix.c  pjlib 1.12.0 for POSIX initialized
 13:55:35.382 sip_endpoint.c  Creating endpoint instance...
 13:55:35.382          pjlib  select() I/O Queue created (0x1aa7540)
 13:55:35.382 sip_endpoint.c  Module "mod-msg-print" registered
 13:55:35.382 sip_transport.  Transport manager created.
 13:55:35.382 sip_endpoint.c  Module "mod-pjsua-log" registered
 13:55:35.382 sip_endpoint.c  Module "mod-tsx-layer" registered
 13:55:35.382 sip_endpoint.c  Module "mod-stateful-util" registered
 13:55:35.382 sip_endpoint.c  Module "mod-ua" registered
 13:55:35.382 sip_endpoint.c  Module "mod-100rel" registered
 13:55:35.382 sip_endpoint.c  Module "mod-pjsua" registered
 13:55:35.382 sip_endpoint.c  Module "mod-invite" registered
 13:55:35.412       pa_dev.c  PortAudio sound library initialized, status=0
 13:55:35.412       pa_dev.c  PortAudio host api count=2
 13:55:35.412       pa_dev.c  Sound device count=9
 13:55:35.412          pjlib  select() I/O Queue created (0x1ae1028)
 13:55:35.425 sip_endpoint.c  Module "mod-evsub" registered
 13:55:35.425 sip_endpoint.c  Module "mod-presence" registered
 13:55:35.425 sip_endpoint.c  Module "mod-mwi" registered
 13:55:35.425 sip_endpoint.c  Module "mod-refer" registered
 13:55:35.425 sip_endpoint.c  Module "mod-pjsua-pres" registered
 13:55:35.425 sip_endpoint.c  Module "mod-pjsua-im" registered
 13:55:35.425 sip_endpoint.c  Module "mod-pjsua-options" registered
 13:55:35.425   pjsua_core.c  1 SIP worker threads created
 13:55:35.425   pjsua_core.c  pjsua version 1.12.0 for Linux-3.2.0.12/x86_64/glibc-2.13 initialized
init successfull
 13:55:35.426   pjsua_core.c  SIP UDP socket reachable at 100.100.100.105:5060
 13:55:35.426   udp0x1af36f0  SIP UDP transport started, published address is 100.100.100.105:5060
 13:55:35.426    pjsua_acc.c  Account sip:100.100.100.105:5060 added with id 0
 13:55:35.427  pjsua_media.c  RTP socket reachable at 100.100.100.105:4000
 13:55:35.427  pjsua_media.c  RTCP socket reachable at 100.100.100.105:4001
 13:55:35.427  pjsua_media.c  RTP socket reachable at 100.100.100.105:4002
 13:55:35.427  pjsua_media.c  RTCP socket reachable at 100.100.100.105:4003
 13:55:35.428  pjsua_media.c  RTP socket reachable at 100.100.100.105:4004
 13:55:35.428  pjsua_media.c  RTCP socket reachable at 100.100.100.105:4005
 13:55:35.429  pjsua_media.c  RTP socket reachable at 100.100.100.105:4006
 13:55:35.429  pjsua_media.c  RTCP socket reachable at 100.100.100.105:4007
QSystemTrayIcon::setVisible: No Icon set

and after closing this is the remaining:
13:55:53.341   pjsua_core.c  Shutting down, flags=0...
 13:55:53.344   pjsua_pres.c  Shutting down presence..
 13:55:53.344  pjsua_media.c  Shutting down media..
 13:55:53.432       pa_dev.c  PortAudio sound library shutting down..
 13:55:54.434   pjsua_core.c  Destroying...
 13:55:54.435 sip_transactio  Stopping transaction layer module
 13:55:54.435 sip_endpoint.c  Module "mod-pjsua-options" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-pjsua-im" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-pjsua-pres" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-pjsua" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-stateful-util" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-refer" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-mwi" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-presence" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-evsub" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-invite" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-100rel" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-ua" unregistered
 13:55:54.435 sip_transactio  Transaction layer module destroyed
 13:55:54.435 sip_endpoint.c  Module "mod-tsx-layer" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-msg-print" unregistered
 13:55:54.435 sip_endpoint.c  Module "mod-pjsua-log" unregistered
 13:55:54.436 sip_endpoint.c  Endpoint 0x1a99608 destroyed
 13:55:54.436   pjsua_core.c  PJSUA destroyed...

Sorry for disturbing you but I have a collage project and I need to get this to work, Regards

**Comment by danleeb** [comment]
Are you sure you have all dependencies installed (especially qt webkit: sudo apt-get install libqtwebkit-dev)? see Readme.md
Also check file permissions and make sure your firewall isn't blocking the requests (when url is set to google, etc.).

If that doesn't solve your problem, you could try the QtSDK webkit examples..

(I'm currently running GreenJ on Ubuntu11.10 (32bit) without issues)

**Comment by mustafa1024m** [comment]
Yes, it is installed:
mustafa@localhost:~$ sudo apt-get install libqtwebkit-dev
[sudo] password for mustafa: 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
libqtwebkit-dev is already the newest version.

tried the others too, I am currently learning Qt using Qt Creator, I have no firewall installed, I will check iptables and some QtWebView examples to see what is wrong and post back, I am using Kubuntu 12.04 Alpha, thank you for your time, Regards.

**Comment by mustafa1024m** [comment]
QWebKit works fine in other examples, now I installed Ubuntu 11.10 32-bit, everything works fine, thank you and regards.

**Comment by danleeb** [comment]
I have to look into the problem when using Kubuntu.

Thank you for your feedback.
