### ISSUE TITLE
Support for ZRTP and/or SRTP

### ISSUE THREAD

**Issue by Sherlock1979** [danleeb/GreenJ#18]
Hello,

I have found your fantastic GreenJ project a fea days ago and I am rather impressed. Thank you for your work.

I am thinking about implementing a soft phone based on GreenJ but I need ZRTP or at least SRTP for it. As far as I know PJSIP support both.

Thanks,

David

**Comment by danleeb** [comment]
Hello David,

I implemented your feature request into branch 1.1.
SRTP can be used by enabling it in the config file (~/.greenj/settings.conf ... under [phone] with settings "srtp=2" and "srtp_signaling=1"); for more information see src/phone/Phone.h Settings class and the PJSIP documentation on SRTP.

**Comment by Sherlock1979** [comment]
Hello,

Thank you very much for your immediate response and solution. I am more than impressed.

I will test it in a few days. By the way, do you plan to add ZRTP sometimes as well? :)

David

**Comment by danleeb** [comment]
ZRTP can be integrated via a third-party library called Zorg (http://www.zrtp.org/pjsip-integration).
I will add the feature to my todo list, but it may take some time ;)
