### ISSUE TITLE
Build trouble JavascriptHandler.cpp

### ISSUE THREAD

**Issue by itsroot** [danleeb/GreenJ#22]
../src/JavascriptHandler.cpp:25:15: error: ‘QtJson::Json’ has not been declared
../src/JavascriptHandler.cpp: In member function ‘void JavascriptHandler::incomingCall(const phone::Call&) const’:
../src/JavascriptHandler.cpp:56:42: error: ‘Json’ has not been declared
../src/JavascriptHandler.cpp: In member function ‘void JavascriptHandler::slotLogMessage(const LogInfo&) const’:
../src/JavascriptHandler.cpp:513:40: error: ‘Json’ has not been declared
make: **\* [../build/linux/JavascriptHandler.o] Error 1

Linux mint 15
QMake version 2.01a  
Using Qt version 4.8.4 in /usr/lib/x86_64-linux-gnu 
GNU Make 3.81

**Comment by danleeb** [comment]
Hello,

I just committed an update to greenj.pro, but I'm not sure if this fixes your problem.
Have you updated the git submodules?
$ git submodule init
$ git submodule update

**Comment by itsroot** [comment]
Thank you so much. This solved my problem.
