### ISSUE TITLE
How do I specify which codecs to use?

### ISSUE THREAD

**Issue by darrenloasby** [danleeb/GreenJ#3]
Hello

Love GreenJ.  A really excellent and flexible SIP phone.

How do I ensure my calls go out as G711a?  I have scoured the docs and can't find anything!

Thanks in advance.

**Comment by danleeb** [comment]
Hello Darren,

I added methods to manage codec priority in branch 1.1 (still work in progress).
You can now get a list of available codecs via li.Phone::getCodecs() and set priorities via li.Phone.setCodecPriority(codec, priority)

Example (for G.711a):

```
var phone = new li.Phone({ ... });
...
phone.setCodecPriority("PCMA", 254);
...
```

This should set PCMA (G.711a) to the highest priority in the list of available codecs.

Further support for codecs is planned - such as adding/removing codecs.

Please let me know if you don't want to switch to 1.1 so I add codec priorities to version 1.0; but I hope this helps for now.
