### ISSUE TITLE
Compatibility with Qt 4.6

### ISSUE THREAD

**Issue by joonis** [danleeb/GreenJ#5]
Hello,

to make GreenJ work with Qt 4.6 you have to modify the file call.cpp and replace the methods `.toMSecsSinceEpoch()` by `.toTime_t() * 1000`.

Now it compiles also on Ubuntu 10.04 and Qt 4.6.

**Comment by joonis** [comment]
I don't know if there is a need for the millisecond part. But it could be added that way:
`x.toTime_t() * 1000 + x.time().msec()`

**Comment by danleeb** [comment]
Hi joonis,

thank you for reporting this issue. I'm working with Qt4.8 at the moment and didn't notice that toMSecsSinceEpoch() was introduced in Qt4.7.

Don't forget to cast it into a qint64, otherwise overflow is an issue. I committed an update to both the master and 1.1 branch.
